### ISSUE TITLE
Need a way to filter events

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#10]
Not all exporters need all events, how should we filter them?

Proposal:
1. if there is no mention then log all events which are captured
2. add an "event_inclusion" line to the exporter which contains a list of patterns (regex?) which can be used on an event received to determine if it should be logged.

**Comment by mengyanw** [comment]
Should the [`logNotebookContentEvents`](https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/310d1a256d2bba2bf9bf81c7bc232c18f72e2d02/configuration_examples/console_exporter/jupyter_jupyterlab_pioneer_config.py#L31) flag (that decides whether to log the entire notebook content or not) also be a part of the filter?
If the events to log are decided based on individual exporters, the original [`activeEvents`](https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/310d1a256d2bba2bf9bf81c7bc232c18f72e2d02/configuration_examples/console_exporter/jupyter_jupyterlab_pioneer_config.py#L16) flag which controls the activated event for all the exporters would be redundant. Or the extension may filter the event library using `activeEvents` first and then `event_inclusion`?
