### ISSUE TITLE
README has links in it which are broken

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#2]
Looks like this link to exporters is broken too:

![image](https://github.com/educational-technology-collective/jupyterlab-pioneer/assets/1355641/def9b083-6b7f-43c9-bdae-9c1be8be6275)

**Comment by mengyanw** [comment]
https://github.com/educational-technology-collective/jupyterlab-pioneer/commit/675a0361ea9f1f641f2fec6e04b4a1733c84afbf
