### ISSUE TITLE
Class docs @mengyanw

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#26]
https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/6ae3a58fee2321c633d339fafe0435529709ff0e/src/producer.ts#L16-L52

**Comment by cab938** [comment]
Ideally we have docs that describe the context of the event as well as any input parameters that the caller might need to define. Imagine I want to hand this off to an undergraduate student, say someone like Barath, and want them to implement a new event or producer to the system, or tell me from log data what actually happened in the UI.

**Comment by mengyanw** [comment]
Event library table: https://jupyterlab-pioneer.readthedocs.io/en/latest/event_library.html
How to implement a custom event extension: https://jupyterlab-pioneer.readthedocs.io/en/latest/custom_event.html
