### ISSUE TITLE
Explaining the metadata exporters

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#27]
https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/6ae3a58fee2321c633d339fafe0435529709ff0e/src/index.ts#L80-L82

**Comment by cab938** [comment]
It would be good to have some docs here to explain a bit what is happening. I'm NOT a TS person, but I'm a little unclear myself what it means if both config.exporters is true and getMetadata('exporters') returns something. I'm going to open another task I think for an architecture walkthrough doc

**Comment by mengyanw** [comment]
if both `notebookPanel.content.model?.getMetadata('exporters')` and `config.exporters` returns something, the exporter configuration from the metadata will override the configuration from the configuration file

**Comment by mengyanw** [comment]
I will add some docs to the code :)
