### ISSUE TITLE
Architecture Doc

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#28]
I'd like to see just a simple architecture document, maybe architecture.md in the docs folder?, which is a mermaid sequence diagram showing how the communication moved between the various components:

https://mermaid.js.org/syntax/sequenceDiagram.html

Have you made such docs before? The mermaid example is a bit weird because they have names of Alice and John, but instead it should be names of classes that are interacting (both TS/Python) and showing the flow between them. There is no single "correct" diagram, the intention is to help people quickly understand how the data flows in the system

**Comment by mengyanw** [comment]
@cab938 The architecture mermaid diagram has been added. I am not entirely sure about whether to introduce more concepts (producer and the event library, more details about events and exporters) here, so I haven't added them yet. Please let me know what you think :)
