### ISSUE TITLE
Put exporters in bulleted list with a link and one sentence description

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#3]
For this:
![image](https://github.com/educational-technology-collective/jupyterlab-pioneer/assets/1355641/9fb1cc5c-d4bb-4ab8-af90-be513c607ace)

How about we have a bulleted list of the exporters which says something like:
- `command_line_exporter` which sends telemetry events to the python console jupyter is running on
- ...

**Comment by mengyanw** [comment]
https://github.com/educational-technology-collective/jupyterlab-pioneer/tree/main#configurations
