### ISSUE TITLE
More docs in configuration example

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#4]
I love that you have a docker compose with full configuration example for this!

Can we put more docs inline in this configuration example in comments?

https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/main/configuration_examples/jupyter_jupyterlab_pioneer_config.py

For instance, what does the activeEvents *mean* vs. the logNotebookContentEvents? When would I have some things active and logged and some things not? For each of the exporters can you have a description of what it means inline with it?

**Comment by mengyanw** [comment]
https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/283c554f7b8a7692ff5f1ea6f6c7e0fb1606d1c2/configuration_examples/all_exporters/jupyter_jupyterlab_pioneer_config.py
