### ISSUE TITLE
Triple quoted docstring for all exporter functions

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#7]
In this file: https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/main/jupyterlab_pioneer/handlers.py

Can you:
1. write a triple quoted docstring for each of the functions please?
2. provide input/output type hints for each function please?

**Comment by mengyanw** [comment]
https://github.com/educational-technology-collective/jupyterlab-pioneer/blob/main/jupyterlab_pioneer/handlers.py#L9-L125
