### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/jupyterlab-pioneer#9]
What do you think about adding an example of how to add a new extension which produces events?

Alternatively, because there is a lot of work to put together a jupyter extension, how about a specific doc which outlines how to create such an extension?

What is the one page things that a developer like Luke could see which tells him all he needs to know about making his hint extension capable of publishing events (assuming he doesn't care about the exporting end of things)?

**Comment by mengyanw** [comment]
@cab938 
[Demo extension](https://github.com/educational-technology-collective/jupyterlab-pioneer-custom-event-demo) that generates telemetry data & creates a pop-up window when a user clicks a specific button.

The demo comes with a doc outlining how to create custom event extensions, the link is [here](https://github.com/educational-technology-collective/jupyterlab-pioneer-custom-event-demo/blob/main/doc/how-to-implement-a-custom-event-extension.md). :)
